### ISSUE TITLE
Poor rendering of "Sandwiches" icon FF 35.0

### ISSUE THREAD

**Issue by orejolaphet** [phetsims/reactants-products-and-leftovers#28]
Test device: Asus
Operating System: Win 8.1 64-bit
Browser: FF 35.0

Severity: Low

Screenshots:

![sandwiches](https://cloud.githubusercontent.com/assets/5631059/5762657/f4ab45c4-9ca0-11e4-925d-7e805e144894.PNG)

Troubleshooting information (do not edit):
Name: Reactants, Products and Leftovers
URL: http://www.colorado.edu/physics/phet/dev/html/reactants-products-and-leftovers/1.0.0-rc.1/reactants-products-and-leftovers_en.html
Version: 1.0.0-rc.1
User Agent: Mozilla/5.0 (Windows NT 6.3; WOW64; rv:35.0) Gecko/20100101 Firefox/35.0
Language: en-US
Window: 1010x482
Pixel Ratio: 1/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0
Vendor: Mozilla (Mozilla)
Vertex: attribs: 16 varying: 10 uniform: 254
Texture: size: 8192 imageUnits: 16 (vertex: 4, combined: 20)
Max viewport: 8192x8192
OES_texture_float: true

**Comment by pixelzoom** [comment]
This problem pops up every time we use an image for icons in the navigation bar. The only way to truly solve it is to either (a) add SVG-image support to Scenery, or (b) draw the icon programmatically. (a) is on PhET's wish list, but is unlikely to happen for awhile, and certainly not before this sim is published. (b) is not possible (or at least very cost-prohibitive) due to how complicated the sandwich image is. 

As has been done in other sims, we can improve the quality somewhat by creating an image that is optimized for the smaller size used in the navigation bar.  First would be to try saving the existing image at the smaller size used by the navigation bar (147x100).  If that doesn't look acceptable, then start modifying the image to reduce the amount of detail in it.

My recommendation is to do nothing about this for the 1.0 release, mark this issue as "deferred", and revisit when we have SVB-image support.  Assigning to @ycarpenterphet for comment.

**Comment by ycarpenterphet** [comment]
@pixelzoom - Can we see how much the quality would be improved by using the smaller image file? If that can offer any improvement, I think we should do that.

For the release of 1.0, I don't think we should do more than that, though - no need to go in and fiddle with the level of detail, until we have SVG image support in scenery.

**Comment by pixelzoom** [comment]
@ycarpenterphet I don't have the .ai file that you used to create the icon for the "Sandwiches" screen. Please send it to me so that I can check it into assets/, and use it to create a smaller navbar icon.

**Comment by pixelzoom** [comment]
FYI... This is only a problem on Win+Firefox. Mac+Firefox looks fine.

**Comment by ycarpenterphet** [comment]
@pixelzoom While I'm at it, is the sandwiches icon the only item in RPAL for which an ai file is needed? I think the bread, cheese, and meat use the ai files from the Java sim (but I can email these to you as well if it's easier).

Is there anything else that isn't drawn programmatically that I should send along?

**Comment by pixelzoom** [comment]
@ycarpenterphet I have bread.ai, meat.ai and cheese.ai.  The only thing missing is the sandwich.  The other screen icons (and all molecules) are drawn programmatically.  Thanks for checking.

**Comment by pixelzoom** [comment]
@orejolaphet and @ycarpenterphet I created a navbar-specific image file for the "Sandwiches" screen, which you can test in this dev version:

http://www.colorado.edu/physics/phet/dev/html/reactants-products-and-leftovers/1.0.0-dev.24/reactants-products-and-leftovers_en.html

Here are screenshots comparing 1.0.0-dev.24 (top) to 1.0.0-rc.1 (bottoms).

![1 0 0-dev 24](https://cloud.githubusercontent.com/assets/3046552/5811005/bcba8b1a-a00c-11e4-8cd7-1a29a9a9fd04.png)

![1 0 0-rc 1](https://cloud.githubusercontent.com/assets/3046552/5811006/c08136cc-a00c-11e4-9e8b-3e5e9940db70.png)

**Comment by ycarpenterphet** [comment]
@pixelzoom - just checking: of the screenshots you posted, is the top one really the new one (dev.24)?

I looked at both on Win 8.1/FF35, and dev24 looks substantially better to me, while rc1 is pixelated.

**Comment by pixelzoom** [comment]
Sorry, I had the screenshots mislabeled. The top one is 1.0.0-rc.1.

I'm going to close this issue.

**Comment by pixelzoom** [comment]
The way that I got this icon looking good was to scale it down to 70x48, so that Firefox doesn't need to scale it down much.  But as @jonathanolson pointed out in https://github.com/phetsims/reactants-products-and-leftovers/issues/28, I forgot about retina displays - which I guess is why 147x100 is recommended as the minimum size. But at that size, the navbar icon will still look lousy on Win+FF. It will look less-lousy than scaling down the home-screen icon, but it will still be somewhat pixelated. 

So... Back to the drawing board. I'll make a 147x100 image, and post screenshots for comparison.

(Very frustrating that this issue keeps coming up over and over, and we have no way to address it.)

**Comment by pixelzoom** [comment]
Here's a new dev version (1.0.0-dev.25) that uses the recommended size for navbar icons (147x100).
http://www.colorado.edu/physics/phet/dev/html/reactants-products-and-leftovers/1.0.0-dev.25/reactants-products-and-leftovers_en.html

Here's a comparison of the icons at the various sizes. What we're stuck with is slightly better looking, but still lousy.

1.0.0-rc.1 (688x469, scaled-down home-screen icon)
![1 0 0-dev 24](https://cloud.githubusercontent.com/assets/3046552/5811005/bcba8b1a-a00c-11e4-8cd7-1a29a9a9fd04.png)

1.0.0-dev.24 (70x48, this looked the best, but doesn't work for retina)
![1 0 0-rc 1](https://cloud.githubusercontent.com/assets/3046552/5811006/c08136cc-a00c-11e4-9e8b-3e5e9940db70.png)

1.0.0-dev.25 (147x100, this is what we're stuck with)
![screenshot_423](https://cloud.githubusercontent.com/assets/3046552/5820877/43ac5928-a085-11e4-98d6-518be80fe666.png)

**Comment by pixelzoom** [comment]
@ycarpenterphet please let me know if 1.0.0-dev.25 is acceptable.

**Comment by ycarpenterphet** [comment]
That's fine for 1.0 release. Closing.
