### ISSUE TITLE
User feedback: Ammonia 

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/reactants-products-and-leftovers#47]
In the html 5 version of this experiment, there is very limited uses for the “making ammonia” part because you can only go up to 8 H2 so students can’t try out any ratios but the lowest one (where you begin with 1N2.) In the old simulation it used to go up at least to 10N2, which was useful to have students explore the higher ratios.

**Comment by pixelzoom** [comment]
> students can’t try out any ratios but the lowest one (where you begin with 1N2.)

Please point out to the user that this is not the case. Students can create ammonia with 2 "ratios":

1N2 + 3H2 -> 2NH3
2N2 + 6H2 -> 4NH3

The Java version provided this additional ratio:

3N2 + 9H2 = 6NH3

That said...  We reduced the maximum number of molecules from 10 to 8 in the HTML5 version due to vertical space constraints.  Increasing the maximum to 10 would require reducing the size of all molecules significantly.

**Comment by oliver-phet** [comment]
Reply sent to user. Will update with any response.

**Comment by oliver-phet** [comment]
User acknowledged. Closing.
