### ISSUE TITLE
screenshot for website

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/reactants-products-and-leftovers#6]
@ycarpenterphet please specify how you'd like the sim to appear on the PhET website. Easiest would be if you could attach a screenshot showing the desired configuration.  The screenshot for the Java version is attached below for your convenience.

![reactants-products-and-leftovers-screenshot](https://cloud.githubusercontent.com/assets/3046552/5096977/003a91be-6f34-11e4-92b1-298147488f89.png)

**Comment by pixelzoom** [comment]
@ycarpenterphet Just a reminder that we're getting closer to needing a screenshot.

**Comment by ycarpenterphet** [comment]
Let's go with this:

![image](https://cloud.githubusercontent.com/assets/4682895/5804955/d7d2ecfc-9fc7-11e4-9241-e1d3f043e684.jpg)

So that I won't forget the rationale -- I had considered a screenshot from the molecules screen, since I think that's more representative of the sim, but BCE and RPAL look so similar at first glance that I think the sandwiches in the screenshot will help make them more distinct on the website.

**Comment by pixelzoom** [comment]
Screenshot taken on iPad2, chrome cropped off the top, sized to 1024x672.  Check in to master and 1.0 branches. Closing.
