### ISSUE TITLE
Oxford commas in sim title?

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/reactants-products-and-leftovers#67]
The title of this sim is (and always has been) "Reactants, Products and Leftovers".  Based on the recent emphasis on the use of Oxford commas, should the title be tweaked to "Reactants, Products, and Leftovers"?

**Comment by arouinfar** [comment]
I do like Oxford commas, so I'd be in favor of adding one to the title of RPAL.

**Comment by ariel-phet** [comment]
Well, I actually think this is a case where the Oxford is not necessarily the best choice.

The Oxford comma is to separate things to be distinct, the classic example I have heard being:

"For breakfast I had eggs, potatoes, toast, and jam"
vs
"For breakfast I had eggs, potatoes, toast and jam"

The first implies you had toast, and ate jam separately, the second implies you had jam on your toast.

Since this sim has reactants on one side, and "Products and Leftovers" on the other, it seems the current title works. Although, these things could also be thought of separately. It does seem also natural if I were thinking about the "cadence" of the title, it flows off the tongue a bit better as separated "Reactants, Products, and Leftovers" making them all distinct.

So, to me, there are arguments for both directions, with slightly different meaning. 

My inclination would be to leave as is, since it is not incorrect if a certain interpretation is used. But fine if we are inclined the other way.

**Comment by pixelzoom** [comment]
I like @ariel-phet's argument against making a change.  But @arouinfar, I'll leave it up to you.

**Comment by arouinfar** [comment]
@ariel-phet does bring up a great point. I would agree that it's better to preserve the "products and leftovers" grouping, so let's leave it as-is @pixelzoom.
