### ISSUE TITLE
Support for UI sound in 1.3 release.

### ISSUE THREAD

**Issue by markgammon** [phetsims/reactants-products-and-leftovers#74]
As part of the work done for https://github.com/phetsims/vegas/issues/77, UI sounds got turned on for this simulation.  Before the sim is published again from master, we should decide whether to turn the UI sounds off, leave them on and design and implement sounds for the rest of the interactions, or publish with a partial sound design.

If the decision is to turn them off, this can be accomplished by adding the following line to the end of the sim's `-main.js` file:

```js
  soundManager.setOutputLevelForCategory( 'user-interface', 0 );
```

**Comment by pixelzoom** [comment]
Work has resume on this sim -- see #78 and #79.

Common code provides good coverage of UI sounds for this sim.  

But the spinners (NumberSpinner) need work. There has been no sound design/implementation for NumberSpinner, so it just has the default "button click" sound.  To be consistent with other "value" controls (slider, etc.) the pitch of the sound should be related to the spinner value -- higher pitch for larger value.  Complicating things a bit is the fact that spinners have a dynamic range.  I discussed with @jbphet, and we see 4 options for this sim:

(1) Disable UI sound for this sim.  Add it in some future release. Hope that NumberSpinner has proper sound by then.

(2) Use NumberSpinner "as is", with the default "button click" sound.  While we can technically say the sim "supports sound", this option doesn't make that sound at all useful to someone who is relying on sound feedback.

(3) Do a proper sound design/implementation for NumberSpinner.  This will involve more people, take longer (probably weeks or months), but will benefit other sims that use NumberSpinner.

(4) Disable the default sounds for NumberSpinner and do something custom for RPAL.  This is something that I could do myself, probably in an afternoon.

@kathy-phet @arouinfar  How do you want to proceed?  If you have resources and it fits the timeline for publishing this sim, I recommend (3).  My second choice is (4).

**Comment by arouinfar** [comment]
NumberSpinner is so integral to this sim. I do not think the default button sound provides particularly useful feedback for the NumberSpinner interaction. I would rather disable sound (1) than leave it as-is (2).

I strongly vote for option (3). I don't know the timeline for this particular sim, but If our goal as a project is to publish sims with a basic inclusive feature set, we need to invest time into common code as these sorts of issues arise. Otherwise, we will just end up kicking the can down the road (to probably just kick it again in the future).

I don't know if alt input is also on the table for this release, but `supportsInteractiveDescription=true` shows good coverage, though we would need to adjust the focus order.

**Comment by pixelzoom** [comment]
@arouinfar and I discussed this issue, in the context of #77.   PhET has published many sims with the current NumberSpinner sounds, and there has been significant work on sound for NumberSpinner - for example https://github.com/phetsims/sun/issues/886.  So we while NumberSpinner might still benefit from revisiting the sound design, we don't think it's a reason to turn sound off here.  Especially since we would lose the sounds that are are related to the Game screen.

So we will proceed with publishing with UI sound in the 1.3 release.

**Comment by pixelzoom** [comment]
This sim has no custom UI sounds, and only uses the default sounds that come with common-code UI components.  Please verify in https://github.com/phetsims/qa/issues/1159.   Close if OK.

**Comment by Nancy-Salpepi** [comment]
UI sounds are on and sound OK to me (when safari lets me hear sound 🫤).
Closing.
