### ISSUE TITLE
AccordionBoxes expand and become off-center with ?stringTest=dynamic

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/reactants-products-and-leftovers#96]
**Test device**
MacBook Air M1 chip

**Operating System**
15.0.1

**Browser**
Safari 18.0.1

**Problem description**
For https://github.com/phetsims/qa/issues/1160, on the Sandwiches and Molecules Screens with stringTest=dynamic, the "Before Reaction" and "After Reaction" accordion panels expand to the right, making them off-center in relation to the variables underneath. This didn't happen in dev.6.

**Steps to reproduce**
1. Add ?stringTest=dynamic to the url
2. Go to either the Sandwiches or Molecules Screen
3. Press the right arrow key twice

**Visuals**
<img width="1218" alt="Screenshot 2024-11-01 at 9 38 36 AM" src="https://github.com/user-attachments/assets/d66fc958-f72d-4c53-97a0-fd5ba907a3a1">

**Comment by pixelzoom** [comment]
Reproduced.  This regression was introduced during dev testing in the fix for https://github.com/phetsims/reactants-products-and-leftovers/issues/93 -- I increased maxWidth too much for the accordion box titles.   This is now fixed in main and 1.3 branches, with a comment in the code cautioning about this particular maxWidth value.

@Nancy-Salpepi please review in main. If it looks OK, change the label to "fixed-awaiting-deploy" for verification in the next RC.

**Comment by Nancy-Salpepi** [comment]
Things look OK with ?stringTest=dynamic but not with ?stringTest=long. 

<img width="1313" alt="Screenshot 2024-11-04 at 11 16 48 AM" src="https://github.com/user-attachments/assets/dfddbe50-9bed-46d3-8aea-4951497660a5">

**Comment by KatieWoe** [comment]
Looks good on main

**Comment by Nancy-Salpepi** [comment]
Looks good in rc.2. Closing.
